use rand::Rng;

pub fn generate_guest_username() -> String {
    let adjectives = [
        "happy",
        "silly",
        "clever",
        "brave",
        "funny",
        "kind",
        "smart",
        "gentle",
        "creative",
        "honest",
        "whimsical",
        "zany",
        "quirky",
        "dazzling",
        "jazzy",
        "snazzy",
        "groovy",
        "cosmic",
        "fluffy",
        "bubbly",
        "sparkly",
        "magical",
        "mystical",
        "legendary",
        "epic",
        "mighty",
        "sneaky",
        "mischievous",
        "fabulous",
        "spectacular",
        "marvelous",
        "fantastic",
        "radical",
        "tubular",
        "bodacious",
        "righteous",
        "awesome",
        "gnarly",
        "wicked",
        "stellar",
        "galactic",
        "quantum",
        "cybernetic",
        "neon",
        "glitchy",
        "pixelated",
        "retro",
        "futuristic",
        "time-traveling",
        "dimensional",
        "rainbow",
        "glittering",
        "shimmering",
    ];

    let nouns = [
        "cat",
        "dog",
        "bird",
        "lion",
        "tiger",
        "elephant",
        "monkey",
        "panda",
        "dolphin",
        "butterfly",
        "unicorn",
        "dragon",
        "phoenix",
        "griffin",
        "mermaid",
        "wizard",
        "ninja",
        "pirate",
        "astronaut",
        "dinosaur",
        "robot",
        "alien",
        "zombie",
        "vampire",
        "werewolf",
        "ghost",
        "goblin",
        "elf",
        "dwarf",
        "giant",
        "fairy",
        "centaur",
        "pegasus",
        "kraken",
        "yeti",
        "sasquatch",
        "cyclops",
        "gorgon",
        "chimera",
        "hydra",
        "sphinx",
        "minotaur",
        "dryad",
        "nymph",
        "siren",
        "banshee",
        "leprechaun",
        "gremlin",
        "troll",
        "ogre",
        "gnome",
        "hobbit",
        "jedi",
        "sith",
        "wookie",
        "klingon",
        "kaiju",
    ];

    let mut rng = rand::thread_rng();
    let random_adjective = adjectives[rng.gen_range(0..adjectives.len())];
    let random_noun = nouns[rng.gen_range(0..nouns.len())];
    let random_number = rng.gen_range(1000..=9999);

    format!("{}_{}_{}", random_adjective, random_noun, random_number)
}
